"""Add rtime_last_played to steam_games

Revision ID: 7c26cc3d6726
Revises: 652cab81527a
Create Date: 2025-09-20 09:33:03.477198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c26cc3d6726'
down_revision = '652cab81527a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_games', sa.Column('rtime_last_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_games', 'rtime_last_played')
    # ### end Alembic commands ###