"""Add deletion fields to User model for GDPR compliance

Revision ID: 9cf1f34537f3
Revises: 7c26cc3d6726
Create Date: 2025-09-21 07:52:04.432280

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9cf1f34537f3"
down_revision = "7c26cc3d6726"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("deletion_scheduled_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deletion_scheduled_at")
    op.drop_column("users", "deletion_requested_at")
    # ### end Alembic commands ###
